output0: pageFault.c pageFault1.c pageFault2.c pageFault3.c pageFault4.c pageFault5.c pageFault6.c pageFault7.c pageFault8.c pageFault9.c output1 output2 output3 output4 output5 output6 output7 output8 output9 plot0 plot0.c plot1 plot1.c runall runall.c
	gcc pageFault.c -o output0
	
output1: pageFault1.c
	gcc pageFault1.c -o output1
	
output2: pageFault2.c
	gcc pageFault2.c -o output2
	
output3: pageFault3.c
	gcc pageFault3.c -o output3
	
output4: pageFault4.c
	gcc pageFault4.c -o output4
	
output5: pageFault5.c
	gcc pageFault5.c -o output5
	
output6: pageFault6.c
	gcc pageFault6.c -o output6

output7: pageFault7.c
	gcc pageFault7.c -o output7
	
output8: pageFault8.c
	gcc pageFault8.c -o output8
	
output9: pageFault9.c
	gcc pageFault9.c -o output9
	
plot0: plot0.c
	gcc plot0.c -o plot0
	
plot1: plot1.c
	gcc plot1.c -o plot1

runall: runall.c
	gcc runall.c -o runall
